#!/bin/sh

# sxhkd &

# will later change this to just source the wal output
for color in $(xrdb -q | grep 'color' | sort -V | awk '{print $2}' | xargs); do
    eval "COLOR${i:=0}=$color"
    true $((i=i+1))
done

MONITORS=$(xrandr -q | grep -w 'connected' | cut -d' ' -f1 | xargs)
NUM_MONITORS=$(echo "$MONITORS" | wc -w)
WSPS=9
WSP_2_MON=$((WSPS/NUM_MONITORS))
WSP_REM=$((WSPS%NUM_MONITORS))

i=1

for mon in $MONITORS; do
    # concatenate the numbers
    for _ in $(seq $WSP_2_MON); do
        numbers="$numbers $i"
        true $((i=i+1))
    done

    # if on the last mon and we have a remainder, concat it
    # black magic ensues
    [ $((i+WSP_REM)) -eq $((WSPS+1)) ] && while [ "$i" -lt $((WSPS+1)) ]; do
        numbers="$numbers $i"
        true $((i=i+1))
    done

    bspc monitor "$mon" -d "$numbers"
    unset numbers
done

# roman numerals are cool but i won't trouble myself with them now
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          4
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color  "$COLOR1"

bspc rule -a Emacs desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Steam desktop='^8'
