;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-insert
        evil-normal-state
        evil-yank
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        sp-backward-delete-char
        ))
